[package]
name = "niancat"
version = "0.1.0"
authors = ["Erik Edin <erikedin.name@gmail.com>"]

[dependencies]
slack = "0.15.0"
regex = "0.1.73"
lazy_static = "0.2.1"
multimap = "0.3.0"
rust-crypto = "0.2.36"
hyper = "0.9.5"